import { StudentInfo } from '../store/student/student.model';

export const studentInfoMock: StudentInfo[] = [
  {
    name: 'Stu A',
    class: 'Class 1',
    Maths: 77,
    English: 62,
    Chemical: 88,
    Chinese: 67,
  },
  {
    name: 'Stu B',
    class: 'Class 1',
    Maths: 75,
    English: 82,
    Chemical: 89,
    Chinese: 64,
  },
  {
    name: 'Stu C',
    class: 'Class 1',
    Maths: 77,
    English: 62,
    Chemical: 88,
    Chinese: 67,
  },
  {
    name: 'Stu D',
    class: 'Class 1',
    Maths: 77,
    English: 62,
    Chemical: 88,
    Chinese: 67,
  },
  {
    name: 'Stu E',
    class: 'Class 2',
    Maths: 77,
    English: 62,
    Chemical: 100,
    Chinese: 67,
  },
  {
    name: 'Stu F',
    class: 'Class 2',
    Maths: 77,
    English: 100,
    Chemical: 88,
    Chinese: 67,
  },
  {
    name: 'Stu J',
    class: 'Class 2',
    Maths: 77,
    English: 92,
    Chemical: 88,
    Chinese: 99,
  },
  {
    name: 'Stu K',
    class: 'Class 2',
    Maths: 77,
    English: 67,
    Chemical: 88,
    Chinese: 67,
  },
  {
    name: 'Stu L',
    class: 'Class 3',
    Maths: 77,
    English: 62,
    Chemical: 88,
    Chinese: 67,
  },
  {
    name: 'Stu M',
    class: 'Class 3',
    Maths: 77,
    English: 62,
    Chemical: 88,
    Chinese: 67,
  },
  {
    name: 'Stu N',
    class: 'Class 3',
    Maths: 56,
    English: 55,
    Chemical: 58,
    Chinese: 57,
  },
  {
    name: 'Stu O',
    class: 'Class 3',
    Maths: 72,
    English: 68,
    Chemical: 89,
    Chinese: 67,
  },
  {
    name: 'Stu P',
    class: 'Class 4',
    Maths: 87,
    English: 72,
    Chemical: 48,
    Chinese: 62,
  },
  {
    name: 'Stu Q',
    class: 'Class 4',
    Maths: 87,
    English: 92,
    Chemical: 88,
    Chinese: 67,
  },
  {
    name: 'Stu R',
    class: 'Class 4',
    Maths: 77,
    English: 65,
    Chemical: 88,
    Chinese: 60,
  },
  {
    name: 'Stu S',
    class: 'Class 4',
    Maths: 67,
    English: 92,
    Chemical: 87,
    Chinese: 89,
  },
];
